Repository wecode-bootcamp-korea/22-Westagram-backend, pull requests merged in 2021-06, with the labels that each got.

#15 [안재경] Mission 1: Django 초기 세팅
  students/jaegyeong-an/.gitignore
  students/jaegyeong-an/.vscode/settings.json
  students/jaegyeong-an/manage.py
  students/jaegyeong-an/requirements.txt
  students/jaegyeong-an/user/__init__.py
  students/jaegyeong-an/user/admin.py
  students/jaegyeong-an/user/apps.py
  students/jaegyeong-an/user/migrations/__init__.py
  students/jaegyeong-an/user/models.py
  students/jaegyeong-an/user/tests.py
  students/jaegyeong-an/user/views.py
  students/jaegyeong-an/westagram/__init__.py
  students/jaegyeong-an/westagram/asgi.py
  students/jaegyeong-an/westagram/settings.py
  students/jaegyeong-an/westagram/urls.py
  students/jaegyeong-an/westagram/wsgi.py
Labels: Status : Accepted

#18 [안희수] Mission 1 : Django 초기 세팅
  students/heesu/manage.py
  students/heesu/westagram/.gitignore
  students/heesu/westagram/__init__.py
  students/heesu/westagram/asgi.py
  students/heesu/westagram/settings.py
  students/heesu/westagram/urls.py
  students/heesu/westagram/wsgi.py
Labels: Status : Accepted

#17 [이준영] Mission 1: Django 초기 세팅
  students/junyoung-lee/.gitignore
  students/junyoung-lee/manage.py
  students/junyoung-lee/westagram/__init__.py
  students/junyoung-lee/westagram/asgi.py
  students/junyoung-lee/westagram/settings.py
  students/junyoung-lee/westagram/urls.py
  students/junyoung-lee/westagram/wsgi.py
Labels: Status: 리뷰 요청

#22 [김한준] Mission 1 : Django 초기 세팅
  students/hanjoon/.gitignore
  students/hanjoon/manage.py
  students/hanjoon/westargram/__init__.py
  students/hanjoon/westargram/asgi.py
  students/hanjoon/westargram/settings.py
  students/hanjoon/westargram/urls.py
  students/hanjoon/westargram/wsgi.py
Labels: Status: 수정 요청

#25 [최준영] Mission 1 : Django 초기 세팅
  students/junyeong-choi/.gitignore
  students/junyeong-choi/manage.py
  students/junyeong-choi/project_westagram/__init__.py
  students/junyeong-choi/project_westagram/asgi.py
  students/junyeong-choi/project_westagram/settings.py
  students/junyeong-choi/project_westagram/urls.py
  students/junyeong-choi/project_westagram/wsgi.py
  students/junyeong-choi/requirements.txt
Labels: Status : Accepted

#27 [전수현] Mission 1: Django 초기 세팅
  students/soohyun-jeon/.gitignore
  students/soohyun-jeon/manage.py
  students/soohyun-jeon/requirements.txt
  students/soohyun-jeon/westagram/__init__.py
  students/soohyun-jeon/westagram/asgi.py
  students/soohyun-jeon/westagram/requirements.txt
  students/soohyun-jeon/westagram/settings.py
  students/soohyun-jeon/westagram/urls.py
  students/soohyun-jeon/westagram/wsgi.py
Labels: Status : Accepted

#29 [안희수] Mission 1 : Django 초기 세팅
  students/heesu/westagram/settings.py
Labels: Status: 리뷰 요청

#30 [이신재] Mission 1 : Django 초기 세팅
  students/sinjae/.gitignore
  students/sinjae/manage.py
  students/sinjae/westagram/__init__.py
  students/sinjae/westagram/asgi.py
  students/sinjae/westagram/settings.py
  students/sinjae/westagram/urls.py
  students/sinjae/westagram/wsgi.py
Labels: Status : Accepted

#31 [이원석] Mission 1 : Django 초기 세팅
  students/wonseok/.gitignore
  students/wonseok/.vscode/settings.json
  students/wonseok/project_westagram/settings.py
  students/wonseok/project_westagram/urls.py
  students/wonseok/user/__init__.py
  students/wonseok/user/admin.py
  students/wonseok/user/apps.py
  students/wonseok/user/migrations/0001_initial.py
  students/wonseok/user/migrations/__init__.py
  students/wonseok/user/models.py
  students/wonseok/user/tests.py
  students/wonseok/user/views.py
Labels: Status : Accepted

#32 [설지우] Mission 1 : Django 초기 세팅
  students/jiwoo/.gitignore
  students/jiwoo/jiwooseol.md
  students/jiwoo/westargram/__init__.py
  students/jiwoo/westargram/asgi.py
  students/jiwoo/westargram/settings.py
  students/jiwoo/westargram/urls.py
  students/jiwoo/westargram/wsgi.py
Labels: Status: 리뷰 요청

#19 [서정민] Mission 1: Django 초기 세팅
  students/jungmin/.gitignore
  students/jungmin/manage.py
  students/jungmin/project_westagram/__init__.py
  students/jungmin/project_westagram/asgi.py
  students/jungmin/project_westagram/settings.py
  students/jungmin/project_westagram/urls.py
  students/jungmin/project_westagram/wsgi.py
Labels: Status : Accepted

#20 [최현정] Mission 1 : Django 초기 세팅
  students/hyeonjung/manage.py
  students/hyeonjung/project_westagram/.gitignore
  students/hyeonjung/project_westagram/__init__.py
  students/hyeonjung/project_westagram/asgi.py
  students/hyeonjung/project_westagram/settings.py
  students/hyeonjung/project_westagram/urls.py
  students/hyeonjung/project_westagram/wsgi.py
Labels: Status : Accepted

#24 [박성준] Mission 1 : Django 초기 세팅
  students/seongjun/.gitignore
  students/seongjun/.idea/.gitignore
  students/seongjun/.idea/inspectionProfiles/Project_Default.xml
  students/seongjun/.idea/inspectionProfiles/profiles_settings.xml
  students/seongjun/.idea/misc.xml
  students/seongjun/.idea/modules.xml
  students/seongjun/.idea/seongjun.iml
  students/seongjun/.idea/vcs.xml
  students/seongjun/manage.py
  students/seongjun/westagram/__init__.py
  students/seongjun/westagram/asgi.py
  students/seongjun/westagram/settings.py
  students/seongjun/westagram/urls.py
  students/seongjun/westagram/wsgi.py
Labels: Status : Accepted

#36 [김태영] Mission 1: Django 초기 세팅
  students/taeyoung/.gitignore
  students/taeyoung/manage.py
  students/taeyoung/westagram/__init__.py
  students/taeyoung/westagram/asgi.py
  students/taeyoung/westagram/settings.py
  students/taeyoung/westagram/urls.py
  students/taeyoung/westagram/wsgi.py
Labels: Status : Accepted

#26 [이성민] Mission 1: Django 초기 세팅
  students/sungmin/project_westagram/__init__.py
  students/sungmin/project_westagram/asgi.py
  students/sungmin/project_westagram/settings.py
  students/sungmin/project_westagram/urls.py
  students/sungmin/project_westagram/wsgi.py
Labels: Status : Accepted

#38 [최명준] Mission 1 Django 초기 세팅
  students/myungjun/.gitignore
  students/myungjun/manage.py
  students/myungjun/project_westagram/__init__.py
  students/myungjun/project_westagram/asgi.py
  students/myungjun/project_westagram/settings.py
  students/myungjun/project_westagram/urls.py
  students/myungjun/project_westagram/wsgi.py
Labels: Status : Accepted

#40 [김예랑] Mission 1 : Django 초기 세팅
  students/yerang/.gitignore
  students/yerang/.vscode/settings.json
  students/yerang/manage.py
  students/yerang/westagram/__init__.py
  students/yerang/westagram/asgi.py
  students/yerang/westagram/settings.py
  students/yerang/westagram/urls.py
  students/yerang/westagram/wsgi.py
Labels: Status : Accepted

#49 [이지훈] Mission 1: Django 초기 세팅
  students/jihoon/.gitignore
  students/jihoon/jihoon/__init__.py
  students/jihoon/jihoon/asgi.py
  students/jihoon/jihoon/settings.py
  students/jihoon/jihoon/urls.py
  students/jihoon/jihoon/wsgi.py
  students/jihoon/manage.py
Labels: Status: 리뷰 요청

#33 [안재경]Mission 2: User Model 생성
  students/jaegyeong-an/.zshrc
  students/jaegyeong-an/user/migrations/0001_initial.py
  students/jaegyeong-an/user/models.py
  students/jaegyeong-an/westagram/settings.py
Labels: Status : Accepted

#45 [서정민] Mission 2: User Model 생성
  students/jungmin/project_westagram/settings.py
  students/jungmin/user/__init__.py
  students/jungmin/user/admin.py
  students/jungmin/user/apps.py
  students/jungmin/user/migrations/0001_initial.py
  students/jungmin/user/migrations/__init__.py
  students/jungmin/user/models.py
  students/jungmin/user/tests.py
  students/jungmin/user/views.py
Labels: Status : Accepted

#55 [이성민] Mission 2: User Model 생성
  students/sungmin/users/__init__.py
  students/sungmin/users/admin.py
  students/sungmin/users/apps.py
  students/sungmin/users/migrations/__init__.py
  students/sungmin/users/models.py
  students/sungmin/users/tests.py
  students/sungmin/users/views.py
Labels: Status : Accepted

#44 [이준영]Mission 2: User Model 생성
  students/junyoung-lee/user/__init__.py
  students/junyoung-lee/user/admin.py
  students/junyoung-lee/user/apps.py
  students/junyoung-lee/user/migrations/0001_initial.py
  students/junyoung-lee/user/migrations/__init__.py
  students/junyoung-lee/user/models.py
  students/junyoung-lee/user/tests.py
  students/junyoung-lee/user/urls.py
  students/junyoung-lee/user/views.py
  students/junyoung-lee/westagram/settings.py
  students/junyoung-lee/westagram/urls.py
Labels: Status : Accepted

#46 [김태영] Mission 2: User Model 생성
  students/taeyoung/users/__init__.py
  students/taeyoung/users/admin.py
  students/taeyoung/users/apps.py
  students/taeyoung/users/migrations/__init__.py
  students/taeyoung/users/models.py
  students/taeyoung/users/tests.py
  students/taeyoung/users/views.py
Labels: Status : Accepted

#52 [최명준] Mission 2: User Model 생성
  students/myungjun/.vscode/settings.json
  students/myungjun/user/__init__.py
  students/myungjun/user/admin.py
  students/myungjun/user/apps.py
  students/myungjun/user/migrations/__init__.py
  students/myungjun/user/models.py
  students/myungjun/user/tests.py
  students/myungjun/user/views.py
Labels: Status : Accepted

#41 [최현정]Mission 2: User Model 생성
  students/hyeonjung/project_westagram/settings.py
  students/hyeonjung/user/__init__.py
  students/hyeonjung/user/admin.py
  students/hyeonjung/user/apps.py
  students/hyeonjung/user/migrations/0001_initial.py
  students/hyeonjung/user/migrations/0002_alter_user_password.py
  students/hyeonjung/user/migrations/__init__.py
  students/hyeonjung/user/models.py
  students/hyeonjung/user/tests.py
  students/hyeonjung/user/views.py
Labels: Status : Accepted

#48 [최준영] Mission 2: User Model 생성
  students/junyeong-choi/accounts/__init__.py
  students/junyeong-choi/accounts/admin.py
  students/junyeong-choi/accounts/apps.py
  students/junyeong-choi/accounts/migrations/0001_initial.py
  students/junyeong-choi/accounts/migrations/0002_auto_20210625_0222.py
  students/junyeong-choi/accounts/migrations/__init__.py
  students/junyeong-choi/accounts/models.py
  students/junyeong-choi/accounts/tests.py
  students/junyeong-choi/accounts/views.py
  students/junyeong-choi/project_westagram/settings.py
Labels: Status : Accepted

#53 [김예랑] Mission 2: User Model 생성
  students/yerang/user/__init__.py
  students/yerang/user/admin.py
  students/yerang/user/apps.py
  students/yerang/user/migrations/0001_initial.py
  students/yerang/user/migrations/__init__.py
  students/yerang/user/models.py
  students/yerang/user/tests.py
  students/yerang/user/views.py
  students/yerang/westagram/settings.py
Labels: Status : Accepted

#54 [이지훈] Mission 2: User Model 생성
  students/jihoon/user/__init__.py
  students/jihoon/user/admin.py
  students/jihoon/user/apps.py
  students/jihoon/user/migrations/__init__.py
  students/jihoon/user/models.py
  students/jihoon/user/tests.py
  students/jihoon/user/views.py
  students/jihoon/westargram/__init__.py
  students/jihoon/westargram/asgi.py
  students/jihoon/westargram/settings.py
  students/jihoon/westargram/urls.py
  students/jihoon/westargram/wsgi.py
Labels: Status : Accepted

#43 [박성준]Mission 2: User Model 생성
  students/seongjun/user/__init__.py
  students/seongjun/user/admin.py
  students/seongjun/user/apps.py
  students/seongjun/user/migrations/0001_initial.py
  students/seongjun/user/migrations/0002_auto_20210625_0108.py
  students/seongjun/user/migrations/0003_auto_20210625_0403.py
  students/seongjun/user/migrations/__init__.py
  students/seongjun/user/models.py
  students/seongjun/user/tests.py
  students/seongjun/user/views.py
  students/seongjun/westagram/settings.py
  students/seongjun/westagram/urls.py
Labels: Status : Accepted

#47 [전수현] Mission 2: User Model 생성
  students/soohyun-jeon/users/__init__.py
  students/soohyun-jeon/users/admin.py
  students/soohyun-jeon/users/apps.py
  students/soohyun-jeon/users/migrations/__init__.py
  students/soohyun-jeon/users/models.py
  students/soohyun-jeon/users/tests.py
  students/soohyun-jeon/users/views.py
  students/soohyun-jeon/westagram/settings.py
Labels: Status: 리뷰 요청

#51 [김한준] Mission 2: User Model 생성
  students/hanjoon/users/__init__.py
  students/hanjoon/users/admin.py
  students/hanjoon/users/apps.py
  students/hanjoon/users/migrations/0001_initial.py
  students/hanjoon/users/migrations/__init__.py
  students/hanjoon/users/models.py
  students/hanjoon/users/tests.py
  students/hanjoon/users/urls.py
  students/hanjoon/westargram/settings.py
  students/hanjoon/westargram/urls.py
Labels: Status : Accepted

#56 [설지우] Mission 2: User Model 생성
  students/jiwoo/manage.py
  students/jiwoo/users/__init__.py
  students/jiwoo/users/admin.py
  students/jiwoo/users/apps.py
  students/jiwoo/users/migrations/0001_initial.py
  students/jiwoo/users/migrations/__init__.py
  students/jiwoo/users/models.py
  students/jiwoo/users/tests.py
  students/jiwoo/users/urls.py
  students/jiwoo/users/views.py
  students/jiwoo/westargram/settings.py
  students/jiwoo/westargram/urls.py
Labels: Status: 리뷰 요청

#42 [안희수]Mission 2: User Model 생성
  students/heesu/users/__init__.py
  students/heesu/users/admin.py
  students/heesu/users/apps.py
  students/heesu/users/migrations/0001_initial.py
  students/heesu/users/migrations/__init__.py
  students/heesu/users/models.py
  students/heesu/users/tests.py
  students/heesu/users/urls.py
  students/heesu/users/views.py
  students/heesu/westagram/settings.py
  students/heesu/westagram/urls.py
Labels: Status : Accepted

#58 [이동명] Mission 2: User Model 생성
  students/dongmyeong/users/__init__.py
  students/dongmyeong/users/admin.py
  students/dongmyeong/users/apps.py
  students/dongmyeong/users/migrations/0001_initial.py
  students/dongmyeong/users/migrations/0002_auto_20210625_0537.py
  students/dongmyeong/users/migrations/__init__.py
  students/dongmyeong/users/models.py
  students/dongmyeong/users/tests.py
  students/dongmyeong/users/views.py
  students/dongmyeong/westagram/settings.py
Labels: Status : Accepted

#50 [이원석] Mission 2: User Model 생성
  students/wonseok/.vscode/settings.json
  students/wonseok/project_westagram/settings.py
  students/wonseok/user/__init__.py
  students/wonseok/user/admin.py
  students/wonseok/user/apps.py
  students/wonseok/user/migrations/0001_initial.py
  students/wonseok/user/migrations/__init__.py
  students/wonseok/user/models.py
  students/wonseok/user/tests.py
  students/wonseok/user/views.py
Labels: Status : Accepted

#57 [이신재] Mission 2: User Model 생성
  students/sinjae/users/__init__.py
  students/sinjae/users/admin.py
  students/sinjae/users/apps.py
  students/sinjae/users/migrations/__init__.py
  students/sinjae/users/models.py
  students/sinjae/users/tests.py
  students/sinjae/users/urls.py
  students/sinjae/users/views.py
Labels: Status: 리뷰 요청

#62 [최명준] Mission 2: User Model 생성
  students/myungjun/project_westagram/settings.py
  students/myungjun/user/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#60 [김예랑] Mission 2: 회원가입 엔드포인트
  students/yerang/user/migrations/0002_auto_20210625_0345.py
  students/yerang/user/urls.py
  students/yerang/user/validation.py
  students/yerang/user/views.py
  students/yerang/westagram/urls.py
Labels: Status : Accepted

#81 [김예랑] Mission 2: 회원가입 엔드포인트
  students/yerang/user/views.py
Labels: Status : Accepted

#70 [이지훈] Mission 2: 회원가입 엔드포인트 구현
  students/jihoon/manage.py
  students/jihoon/user/migrations/0001_initial.py
  students/jihoon/user/migrations/0002_alter_account_nickname.py
  students/jihoon/user/models.py
  students/jihoon/user/urls.py
  students/jihoon/user/views.py
  students/jihoon/westargram/asgi.py
  students/jihoon/westargram/settings.py
  students/jihoon/westargram/urls.py
  students/jihoon/westargram/wsgi.py
Labels: Status : Accepted

#64 [이준영] Mission 2: 회원가입 엔드포인트
  students/junyoung-lee/user/urls.py
  students/junyoung-lee/user/validators.py
  students/junyoung-lee/user/views.py
  students/junyoung-lee/westagram/urls.py
Labels: Status: 리뷰 요청

#59 [최현정] Mission 2: 회원가입 엔드포인트
  students/hyeonjung/project_westagram/urls.py
  students/hyeonjung/user/urls.py
  students/hyeonjung/user/views.py
Labels: Status : Accepted

#77 [이원석] Mission 2: 회원가입 엔드포인트
  students/wonseok/project_westagram/urls.py
  students/wonseok/user/migrations/0001_initial.py
  students/wonseok/user/models.py
  students/wonseok/user/urls.py
  students/wonseok/user/validation.py
  students/wonseok/user/views.py
Labels: Status : Accepted

#61 [안재경] Mission2: 회원가입 엔드포인트 구현
  students/jaegyeong-an/user/migrations/0002_auto_20210625_0427.py
  students/jaegyeong-an/user/tests.py
  students/jaegyeong-an/user/urls.py
  students/jaegyeong-an/user/views.py
  students/jaegyeong-an/westagram/urls.py
Labels: Status : Accepted

#80 [이성민] Mission 2: 회원가입 엔드포인트
  students/sungmin/.gitignore
  students/sungmin/manage.py
  students/sungmin/project_westagram/settings.py
  students/sungmin/project_westagram/urls.py
  students/sungmin/users/migrations/0001_initial.py
  students/sungmin/users/models.py
  students/sungmin/users/urls.py
  students/sungmin/users/views.py
Labels: Status : Accepted

#78 [김태영] Mission 2: 회원가입 엔드포인트
  students/taeyoung/users/urls.py
  students/taeyoung/users/views.py
Labels: Status : Accepted

#66 [김한준] Mission 2: 회원가입 엔드포인트 구현
  students/hanjoon/users/migrations/0002_auto_20210625_0541.py
  students/hanjoon/users/models.py
  students/hanjoon/users/urls.py
  students/hanjoon/users/views.py
  students/hanjoon/westargram/urls.py
Labels: Status : Accepted

#67 [전수현]Mission2 : 회원가입 엔드포인트 구현
  students/soohyun-jeon/users/migrations/0001_initial.py
  students/soohyun-jeon/users/migrations/0002_auto_20210625_1746.py
  students/soohyun-jeon/users/models.py
  students/soohyun-jeon/users/urls.py
  students/soohyun-jeon/users/validators.py
  students/soohyun-jeon/users/views.py
  students/soohyun-jeon/westagram/settings.py
  students/soohyun-jeon/westagram/urls.py
Labels: Status : Accepted

#68 [서정민] Mission 2: 회원가입 엔드포인트 구현
  students/jungmin/project_westagram/urls.py
  students/jungmin/user/migrations/0002_auto_20210625_0849.py
  students/jungmin/user/models.py
  students/jungmin/user/urls.py
  students/jungmin/user/validators.py
  students/jungmin/user/views.py
Labels: Status : Accepted

#72 [최준영] Mission2: 회원가입 엔드포인트 구현
  students/junyeong-choi/accounts/migrations/0003_auto_20210625_1056.py
  students/junyeong-choi/accounts/models.py
  students/junyeong-choi/accounts/urls.py
  students/junyeong-choi/accounts/views.py
  students/junyeong-choi/project_westagram/urls.py
  students/junyeong-choi/views.py
Labels: Status : Accepted

#75 [박성준] Mission 2: 회원가입 엔드포인트
  students/seongjun/user/migrations/0004_auto_20210625_1351.py
  students/seongjun/user/models.py
  students/seongjun/user/urls.py
  students/seongjun/user/validators.py
  students/seongjun/user/views.py
  students/seongjun/westagram/urls.py
Labels: Status : Accepted

#65 [설지우] Mission2: 회원가입 엔드포인트 구현
  students/jiwoo/users/migrations/0002_auto_20210625_1834.py
  students/jiwoo/users/models.py
  students/jiwoo/users/urls.py
  students/jiwoo/users/validations.py
  students/jiwoo/users/views.py
  students/jiwoo/westargram/settings.py
  students/jiwoo/westargram/urls.py
Labels: Status : Accepted

#74 [이동명] Mission 2: 회원가입 엔드포인트
  students/dongmyeong/users/urls.py
  students/dongmyeong/users/validator.py
  students/dongmyeong/users/views.py
  students/dongmyeong/westagram/urls.py
Labels: Status : Accepted

#76 [안희수] Mission 2: 회원가입 엔드포인트
  students/heesu/users/urls.py
  students/heesu/users/validation.py
  students/heesu/users/views.py
  students/heesu/westagram/urls.py
Labels: Status: 리뷰 요청

#79 [최명준] Mission 2: 회원가입 엔드포인트
  students/myungjun/project_westagram/urls.py
  students/myungjun/user/.vscode/settings.json
  students/myungjun/user/urls.py
  students/myungjun/user/validation.py
  students/myungjun/user/views.py
Labels: Status : Accepted

#113 [박성준] Mission 3: 로그인 엔드포인트
  students/seongjun/user/urls.py
  students/seongjun/user/views.py
Labels: Status : Accepted

#107 [안재경] Mission3 : 로그인 엔드포인트 구현
  students/jaegyeong-an/user/urls.py
  students/jaegyeong-an/user/views.py
Labels: Status : Accepted

#69 [김예랑] Mission 3: 로그인 엔드포인트 구현
  students/yerang/user/urls.py
  students/yerang/user/views.py
  students/yerang/westagram/urls.py
Labels: Status: 리뷰 요청

#83 [이동명] Mission 3: 로그인 엔드포인트
  students/dongmyeong/users/urls.py
  students/dongmyeong/users/views.py
Labels: Status : Accepted

#104 [이지훈] Mission 3: 로그인 엔드포인트:
  students/jihoon/user/urls.py
  students/jihoon/user/views.py
Labels: Status: 리뷰 요청

#105 [이준영] Mission 3: 로그인 엔드포인트
  students/junyoung-lee/user/urls.py
  students/junyoung-lee/user/views.py
Labels: Status : Accepted

#73 [이신재] Mission2: 회원가입 엔드포인트 구현
  students/sinjae/users/migrations/0001_initial.py
  students/sinjae/users/models.py
  students/sinjae/users/urls.py
  students/sinjae/users/validation.py
  students/sinjae/users/views.py
  students/sinjae/westagram/settings.py
  students/sinjae/westagram/urls.py
Labels: Status : Accepted

#106 [최현정] Mission 3: 로그인 엔드포인트
  students/hyeonjung/user/migrations/0001_initial.py
  students/hyeonjung/user/migrations/0002_alter_user_password.py
  students/hyeonjung/user/urls.py
  students/hyeonjung/user/views.py
Labels: Status: 리뷰 요청

#109 [최준영] Mission 3: 로그인 엔드포인트
  students/junyeong-choi/accounts/urls.py
  students/junyeong-choi/accounts/views.py
Labels: Status : Accepted

#110 [김태영] Mission3 : 로그인 엔드포인트
  students/taeyoung/users/urls.py
  students/taeyoung/users/views.py
  students/taeyoung/westagram/settings.py
  students/taeyoung/westagram/urls.py
Labels: Status : Accepted

#112 [서정민] Mission 3: 로그인 엔드포인트
  students/jungmin/user/urls.py
  students/jungmin/user/views.py
Labels: Status: 리뷰 요청

#125 [최명준] Mission 2: 회원가입 엔드포인트
  students/myungjun/user/urls.py
  students/myungjun/user/views.py
Labels: Status : Accepted

#117 [전수현] Mission 3: 로그인 엔드포인트
  students/soohyun-jeon/users/urls.py
  students/soohyun-jeon/users/views.py
Labels: Status: 리뷰 요청

#108 [김한준] Mission3 : 로그인 엔드포인트
  students/hanjoon/.vscode/settings.json
  students/hanjoon/users/migrations/0003_alter_user_nickname.py
  students/hanjoon/users/models.py
  students/hanjoon/users/urls.py
  students/hanjoon/users/views.py
Labels: Status: 리뷰 요청

#115 [이원석] Mission 2: 회원가입 엔드포인트 (암호화)
  students/wonseok/project_westagram/settings.py
  students/wonseok/user/migrations/0001_initial.py
  students/wonseok/user/models.py
  students/wonseok/user/views.py
Labels: Status: 리뷰 요청

#118 [이동명] Mission 3-1: 로그인 엔드포인트(암호화)
  students/dongmyeong/users/views.py
Labels: Status : Accepted

#126 [서정민] Mission 2: 회원가입 엔드포인트 (암호화)
  students/jungmin/user/views.py
Labels: Status : Accepted

#127 [이준영] Mission 2: 회원가입 엔드포인트 암호화
  students/junyoung-lee/user/urls.py
  students/junyoung-lee/user/views.py
Labels: Status : Accepted

#130 [이성민] Mission 3 : 로그인 엔드포인트
  students/sungmin/users/urls.py
  students/sungmin/users/views.py
Labels: Status : Accepted

#131 [이준영] Mission 3: 로그인 엔드포인트 암호화
  students/junyoung-lee/user/urls.py
  students/junyoung-lee/user/views.py
Labels: Status : Accepted

#129 [서정민] Mission 3: 로그인 엔드포인트 (암호화)
  students/jungmin/user/views.py
Labels: Status : Accepted

#136 [최현정] Mission 3: 로그인 엔드포인트 (암호화)
  students/hyeonjung/user/views.py
Labels: Status: 수정 요청

#133 [최명준] Mission 3: 로그인 엔드포인트
  students/myungjun/user/urls.py
  students/myungjun/user/views.py
Labels: Status: 수정 요청

#135 [김예랑] Mission 3: 로그인 엔드포인트 (암호화)
  students/yerang/user/urls.py
  students/yerang/user/utils.py
  students/yerang/user/views.py
Labels: Status : Accepted

#138 [이신재] Mission 3 : 로그인 엔드포인트(암호화)
  students/sinjae/users/views.py
Labels: Status: 리뷰 요청

#132 [안재경] Mission 3: 회원가입, 로그인 엔드포인트 암호화
  students/jaegyeong-an/user/utils.py
  students/jaegyeong-an/user/views.py
Labels: Status: 리뷰 요청

#119 [안희수] Mission 3: 로그인 엔드포인트
  students/heesu/users/urls.py
  students/heesu/users/views.py
Labels: Status : Accepted

#139 [최준영] Mission 2: 회원가입 엔드포인트 (암호화)
  students/junyeong-choi/accounts/views.py
Labels: Status : Accepted

#134 [김태영] Mission 3: 로그인 엔드포인트 (암호화)
  students/taeyoung/users/views.py
Labels: Status : Accepted

#140 [김한준] Mission 3: 회원가입 앤드포인트 암호화
  students/hanjoon/users/views.py
Labels: Status : Accepted

#141 [박성준] Mission 2: 회원가입 엔드포인트 (암호화)
  students/seongjun/user/views.py
Labels: Status : Accepted

#142 [최준영] Mission 3: 로그인 엔드포인트(암호화)
  students/junyeong-choi/accounts/utils.py
  students/junyeong-choi/accounts/views.py
Labels: Status: 리뷰 요청

#120 [설지우] Mission 3: 로그인 엔드포인트(암호화)
  students/jiwoo/users/urls.py
  students/jiwoo/users/validations.py
  students/jiwoo/users/views.py
Labels: Status : Accepted

#146 [전수현] Mission 3: 회원가입&로그인 엔드포인트(암호화)
  students/soohyun-jeon/.vscode/settings.json
  students/soohyun-jeon/users/views.py
  students/soohyun-jeon/westagram/settings.py
Labels: Status : Accepted

#145 [이성민] Mission 3: 로그인 엔드포인트(암호화)
  students/sungmin/users/views.py
Labels: Status : Accepted

#144 [최명준] Mission 3: 로그인 엔드포인트(암호화)
  students/myungjun/user/views.py
Labels: Status : Accepted

#143 [박성준] Mission 3: 로그인 엔드포인트(암호화)
  students/seongjun/user/views.py
Labels: Status: 리뷰 요청
